apiVersion: v1
kind: Service
metadata:
  name: omniknow-backend
  namespace: omniknow
spec:
  type: ClusterIP
  selector:
    app: omniknow-backend
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http